ctr_model:
    embed_dim: 32
    
    learning_rate: 1e-3
    weight_decay: 1e-6

    scheduler: reduce_lr_on_plateau


language_model:
    hidden_layers: [] #[256]
    activation: relu
    dropout: 0.0