# ---------- Amazon ---------------
# --------- MovieLens ----------
ctr_model:
    combination: parallel
    low_rank: ~
    num_experts: ~
    num_layers: 2
    mlp_layer: [128, 64, 64]
    activation: relu
    cross_activation: tanh
    dropout: 0.5
    batch_norm: True

    
    learning_rate: 4e-3
    weight_decay: 8e-2
