# ---------- Amazon ---------------
ctr_model:
    mlp_layer: [128, 64, 64]
    activation: relu
    dropout: 0.5

    batch_norm: True

    learning_rate: 5e-3
    weight_decay: 1e-6

# --------- MovieLens ----------
# ctr_model:
#     mlp_layer: [128, 64, 64]
#     activation: relu
#     dropout: 0.0

#     batch_norm: True

#     learning_rate: 7e-3
#     weight_decay: 7e-2