model:
  embed_dim: 64
  hidden_size: 128
  layer_num: 2
  head_num: 2
  dropout_rate: 0.5
  activation: 'gelu'
  layer_norm_eps: 1e-12

train:
  negative_count: 1
  init_method: normal

eval:
  cutoff: [10, 20, 5, 50, 100]
  val_metrics: [ndcg, recall, mrr]
  val_n_epoch: 1
  test_metrics: [ndcg, recall, precision, map, mrr, hit]
  topk: 150
